fixtures:
  symlinks:
    server: "#{source_dir}"
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.1.0"
    firewall:
      repo: "git://github.com/puppetlabs/puppetlabs-firewall.git"
      ref: "0.4.2"
    ntp:
      repo: "git://github.com/puppetlabs/puppetlabs-ntp.git"
      ref: "3.0.0"
    timezone:
      repo: "git://github.com/saz/puppet-timezone.git"
      ref: "v2.0.0"
